kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels: 
    env: DEV
    containers: labels
    application: Minikube
  annotations:
    domain: vinodhub.online
spec:
  containers:
    - name: nginx
      image: nginx:latest