kind: Pod
apiVersion: v1
metadata: 
  name: stress
spec:
  containers:
    - name: stress
      image: kanalavinodkumar/stress:v1
      command: ["sleep", "2000"]
      resources:
        requests:
          cpu: "0.2"
          memory: "128Mi"
        limits:
          cpu: "0.4"
          memory: "256Mi"