kind: Pod
apiVersion: v1
metadata: 
  name: resources
  namespace: roboshop
spec:
  containers:
    - name: stress
      image: kanalavinodkumar/stress:v1
      command: ["sleep", "2000"]
      resources:
        requests:
          cpu: "0.2"
          memory: "128mi"
        limits:
          cpu: "0.4"
          memory: "160mi"