kind: Pod
apiVersion: v1
metadata:
  name: config-pod
spec:
  containers:
    - name: config-pod
      image: nginx:latest
      env:
        - name: Domain
          valueFrom: 
            configMapKeyRef:
              name: config-map-test
              key: Domain
        - name: Tech-Lead
          valueFrom: 
            configMapKeyRef:
              name: config-map-test
              key: Tech-Lead