kind: Pod
apiVersion: v1
metadata:
  name: secret-test
spec:
  containers:
    name: secret-test
    image: nginx:latest
    env:
    - name: AWS_USERNAME
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: username
    - name: AWS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: aws-creds
          key: password